# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/erikparreira/Dropbox/Programming/networkplayground

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/erikparreira/Dropbox/Programming/networkplayground

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erikparreira/Dropbox/Programming/networkplayground/CMakeFiles /Users/erikparreira/Dropbox/Programming/networkplayground/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erikparreira/Dropbox/Programming/networkplayground/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

networkplayground/src/IO/MemoryBitStream.o: networkplayground/src/IO/MemoryBitStream.cpp.o

.PHONY : networkplayground/src/IO/MemoryBitStream.o

# target to build an object file
networkplayground/src/IO/MemoryBitStream.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/IO/MemoryBitStream.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/IO/MemoryBitStream.cpp.o
.PHONY : networkplayground/src/IO/MemoryBitStream.cpp.o

networkplayground/src/IO/MemoryBitStream.i: networkplayground/src/IO/MemoryBitStream.cpp.i

.PHONY : networkplayground/src/IO/MemoryBitStream.i

# target to preprocess a source file
networkplayground/src/IO/MemoryBitStream.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/IO/MemoryBitStream.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/IO/MemoryBitStream.cpp.i
.PHONY : networkplayground/src/IO/MemoryBitStream.cpp.i

networkplayground/src/IO/MemoryBitStream.s: networkplayground/src/IO/MemoryBitStream.cpp.s

.PHONY : networkplayground/src/IO/MemoryBitStream.s

# target to generate assembly for a file
networkplayground/src/IO/MemoryBitStream.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/IO/MemoryBitStream.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/IO/MemoryBitStream.cpp.s
.PHONY : networkplayground/src/IO/MemoryBitStream.cpp.s

networkplayground/src/gameobjects/Engine.o: networkplayground/src/gameobjects/Engine.cpp.o

.PHONY : networkplayground/src/gameobjects/Engine.o

# target to build an object file
networkplayground/src/gameobjects/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Engine.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Engine.cpp.o
.PHONY : networkplayground/src/gameobjects/Engine.cpp.o

networkplayground/src/gameobjects/Engine.i: networkplayground/src/gameobjects/Engine.cpp.i

.PHONY : networkplayground/src/gameobjects/Engine.i

# target to preprocess a source file
networkplayground/src/gameobjects/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Engine.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Engine.cpp.i
.PHONY : networkplayground/src/gameobjects/Engine.cpp.i

networkplayground/src/gameobjects/Engine.s: networkplayground/src/gameobjects/Engine.cpp.s

.PHONY : networkplayground/src/gameobjects/Engine.s

# target to generate assembly for a file
networkplayground/src/gameobjects/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Engine.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Engine.cpp.s
.PHONY : networkplayground/src/gameobjects/Engine.cpp.s

networkplayground/src/gameobjects/GameObject.o: networkplayground/src/gameobjects/GameObject.cpp.o

.PHONY : networkplayground/src/gameobjects/GameObject.o

# target to build an object file
networkplayground/src/gameobjects/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/GameObject.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/GameObject.cpp.o
.PHONY : networkplayground/src/gameobjects/GameObject.cpp.o

networkplayground/src/gameobjects/GameObject.i: networkplayground/src/gameobjects/GameObject.cpp.i

.PHONY : networkplayground/src/gameobjects/GameObject.i

# target to preprocess a source file
networkplayground/src/gameobjects/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/GameObject.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/GameObject.cpp.i
.PHONY : networkplayground/src/gameobjects/GameObject.cpp.i

networkplayground/src/gameobjects/GameObject.s: networkplayground/src/gameobjects/GameObject.cpp.s

.PHONY : networkplayground/src/gameobjects/GameObject.s

# target to generate assembly for a file
networkplayground/src/gameobjects/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/GameObject.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/GameObject.cpp.s
.PHONY : networkplayground/src/gameobjects/GameObject.cpp.s

networkplayground/src/gameobjects/GameObjectRegistry.o: networkplayground/src/gameobjects/GameObjectRegistry.cpp.o

.PHONY : networkplayground/src/gameobjects/GameObjectRegistry.o

# target to build an object file
networkplayground/src/gameobjects/GameObjectRegistry.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/GameObjectRegistry.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/GameObjectRegistry.cpp.o
.PHONY : networkplayground/src/gameobjects/GameObjectRegistry.cpp.o

networkplayground/src/gameobjects/GameObjectRegistry.i: networkplayground/src/gameobjects/GameObjectRegistry.cpp.i

.PHONY : networkplayground/src/gameobjects/GameObjectRegistry.i

# target to preprocess a source file
networkplayground/src/gameobjects/GameObjectRegistry.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/GameObjectRegistry.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/GameObjectRegistry.cpp.i
.PHONY : networkplayground/src/gameobjects/GameObjectRegistry.cpp.i

networkplayground/src/gameobjects/GameObjectRegistry.s: networkplayground/src/gameobjects/GameObjectRegistry.cpp.s

.PHONY : networkplayground/src/gameobjects/GameObjectRegistry.s

# target to generate assembly for a file
networkplayground/src/gameobjects/GameObjectRegistry.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/GameObjectRegistry.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/GameObjectRegistry.cpp.s
.PHONY : networkplayground/src/gameobjects/GameObjectRegistry.cpp.s

networkplayground/src/gameobjects/InputState.o: networkplayground/src/gameobjects/InputState.cpp.o

.PHONY : networkplayground/src/gameobjects/InputState.o

# target to build an object file
networkplayground/src/gameobjects/InputState.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/InputState.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/InputState.cpp.o
.PHONY : networkplayground/src/gameobjects/InputState.cpp.o

networkplayground/src/gameobjects/InputState.i: networkplayground/src/gameobjects/InputState.cpp.i

.PHONY : networkplayground/src/gameobjects/InputState.i

# target to preprocess a source file
networkplayground/src/gameobjects/InputState.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/InputState.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/InputState.cpp.i
.PHONY : networkplayground/src/gameobjects/InputState.cpp.i

networkplayground/src/gameobjects/InputState.s: networkplayground/src/gameobjects/InputState.cpp.s

.PHONY : networkplayground/src/gameobjects/InputState.s

# target to generate assembly for a file
networkplayground/src/gameobjects/InputState.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/InputState.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/InputState.cpp.s
.PHONY : networkplayground/src/gameobjects/InputState.cpp.s

networkplayground/src/gameobjects/Move.o: networkplayground/src/gameobjects/Move.cpp.o

.PHONY : networkplayground/src/gameobjects/Move.o

# target to build an object file
networkplayground/src/gameobjects/Move.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Move.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Move.cpp.o
.PHONY : networkplayground/src/gameobjects/Move.cpp.o

networkplayground/src/gameobjects/Move.i: networkplayground/src/gameobjects/Move.cpp.i

.PHONY : networkplayground/src/gameobjects/Move.i

# target to preprocess a source file
networkplayground/src/gameobjects/Move.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Move.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Move.cpp.i
.PHONY : networkplayground/src/gameobjects/Move.cpp.i

networkplayground/src/gameobjects/Move.s: networkplayground/src/gameobjects/Move.cpp.s

.PHONY : networkplayground/src/gameobjects/Move.s

# target to generate assembly for a file
networkplayground/src/gameobjects/Move.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Move.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Move.cpp.s
.PHONY : networkplayground/src/gameobjects/Move.cpp.s

networkplayground/src/gameobjects/MoveList.o: networkplayground/src/gameobjects/MoveList.cpp.o

.PHONY : networkplayground/src/gameobjects/MoveList.o

# target to build an object file
networkplayground/src/gameobjects/MoveList.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/MoveList.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/MoveList.cpp.o
.PHONY : networkplayground/src/gameobjects/MoveList.cpp.o

networkplayground/src/gameobjects/MoveList.i: networkplayground/src/gameobjects/MoveList.cpp.i

.PHONY : networkplayground/src/gameobjects/MoveList.i

# target to preprocess a source file
networkplayground/src/gameobjects/MoveList.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/MoveList.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/MoveList.cpp.i
.PHONY : networkplayground/src/gameobjects/MoveList.cpp.i

networkplayground/src/gameobjects/MoveList.s: networkplayground/src/gameobjects/MoveList.cpp.s

.PHONY : networkplayground/src/gameobjects/MoveList.s

# target to generate assembly for a file
networkplayground/src/gameobjects/MoveList.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/MoveList.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/MoveList.cpp.s
.PHONY : networkplayground/src/gameobjects/MoveList.cpp.s

networkplayground/src/gameobjects/Player.o: networkplayground/src/gameobjects/Player.cpp.o

.PHONY : networkplayground/src/gameobjects/Player.o

# target to build an object file
networkplayground/src/gameobjects/Player.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Player.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Player.cpp.o
.PHONY : networkplayground/src/gameobjects/Player.cpp.o

networkplayground/src/gameobjects/Player.i: networkplayground/src/gameobjects/Player.cpp.i

.PHONY : networkplayground/src/gameobjects/Player.i

# target to preprocess a source file
networkplayground/src/gameobjects/Player.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Player.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Player.cpp.i
.PHONY : networkplayground/src/gameobjects/Player.cpp.i

networkplayground/src/gameobjects/Player.s: networkplayground/src/gameobjects/Player.cpp.s

.PHONY : networkplayground/src/gameobjects/Player.s

# target to generate assembly for a file
networkplayground/src/gameobjects/Player.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/Player.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/Player.cpp.s
.PHONY : networkplayground/src/gameobjects/Player.cpp.s

networkplayground/src/gameobjects/PlayerMessage.o: networkplayground/src/gameobjects/PlayerMessage.cpp.o

.PHONY : networkplayground/src/gameobjects/PlayerMessage.o

# target to build an object file
networkplayground/src/gameobjects/PlayerMessage.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/PlayerMessage.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/PlayerMessage.cpp.o
.PHONY : networkplayground/src/gameobjects/PlayerMessage.cpp.o

networkplayground/src/gameobjects/PlayerMessage.i: networkplayground/src/gameobjects/PlayerMessage.cpp.i

.PHONY : networkplayground/src/gameobjects/PlayerMessage.i

# target to preprocess a source file
networkplayground/src/gameobjects/PlayerMessage.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/PlayerMessage.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/PlayerMessage.cpp.i
.PHONY : networkplayground/src/gameobjects/PlayerMessage.cpp.i

networkplayground/src/gameobjects/PlayerMessage.s: networkplayground/src/gameobjects/PlayerMessage.cpp.s

.PHONY : networkplayground/src/gameobjects/PlayerMessage.s

# target to generate assembly for a file
networkplayground/src/gameobjects/PlayerMessage.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/PlayerMessage.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/PlayerMessage.cpp.s
.PHONY : networkplayground/src/gameobjects/PlayerMessage.cpp.s

networkplayground/src/gameobjects/World.o: networkplayground/src/gameobjects/World.cpp.o

.PHONY : networkplayground/src/gameobjects/World.o

# target to build an object file
networkplayground/src/gameobjects/World.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/World.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/World.cpp.o
.PHONY : networkplayground/src/gameobjects/World.cpp.o

networkplayground/src/gameobjects/World.i: networkplayground/src/gameobjects/World.cpp.i

.PHONY : networkplayground/src/gameobjects/World.i

# target to preprocess a source file
networkplayground/src/gameobjects/World.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/World.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/World.cpp.i
.PHONY : networkplayground/src/gameobjects/World.cpp.i

networkplayground/src/gameobjects/World.s: networkplayground/src/gameobjects/World.cpp.s

.PHONY : networkplayground/src/gameobjects/World.s

# target to generate assembly for a file
networkplayground/src/gameobjects/World.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/gameobjects/World.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/gameobjects/World.cpp.s
.PHONY : networkplayground/src/gameobjects/World.cpp.s

networkplayground/src/math/Vector3.o: networkplayground/src/math/Vector3.cpp.o

.PHONY : networkplayground/src/math/Vector3.o

# target to build an object file
networkplayground/src/math/Vector3.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/math/Vector3.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/math/Vector3.cpp.o
.PHONY : networkplayground/src/math/Vector3.cpp.o

networkplayground/src/math/Vector3.i: networkplayground/src/math/Vector3.cpp.i

.PHONY : networkplayground/src/math/Vector3.i

# target to preprocess a source file
networkplayground/src/math/Vector3.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/math/Vector3.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/math/Vector3.cpp.i
.PHONY : networkplayground/src/math/Vector3.cpp.i

networkplayground/src/math/Vector3.s: networkplayground/src/math/Vector3.cpp.s

.PHONY : networkplayground/src/math/Vector3.s

# target to generate assembly for a file
networkplayground/src/math/Vector3.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/math/Vector3.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/math/Vector3.cpp.s
.PHONY : networkplayground/src/math/Vector3.cpp.s

networkplayground/src/networking/AckRange.o: networkplayground/src/networking/AckRange.cpp.o

.PHONY : networkplayground/src/networking/AckRange.o

# target to build an object file
networkplayground/src/networking/AckRange.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/AckRange.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/AckRange.cpp.o
.PHONY : networkplayground/src/networking/AckRange.cpp.o

networkplayground/src/networking/AckRange.i: networkplayground/src/networking/AckRange.cpp.i

.PHONY : networkplayground/src/networking/AckRange.i

# target to preprocess a source file
networkplayground/src/networking/AckRange.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/AckRange.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/AckRange.cpp.i
.PHONY : networkplayground/src/networking/AckRange.cpp.i

networkplayground/src/networking/AckRange.s: networkplayground/src/networking/AckRange.cpp.s

.PHONY : networkplayground/src/networking/AckRange.s

# target to generate assembly for a file
networkplayground/src/networking/AckRange.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/AckRange.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/AckRange.cpp.s
.PHONY : networkplayground/src/networking/AckRange.cpp.s

networkplayground/src/networking/DeliveryNotificationManager.o: networkplayground/src/networking/DeliveryNotificationManager.cpp.o

.PHONY : networkplayground/src/networking/DeliveryNotificationManager.o

# target to build an object file
networkplayground/src/networking/DeliveryNotificationManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/DeliveryNotificationManager.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/DeliveryNotificationManager.cpp.o
.PHONY : networkplayground/src/networking/DeliveryNotificationManager.cpp.o

networkplayground/src/networking/DeliveryNotificationManager.i: networkplayground/src/networking/DeliveryNotificationManager.cpp.i

.PHONY : networkplayground/src/networking/DeliveryNotificationManager.i

# target to preprocess a source file
networkplayground/src/networking/DeliveryNotificationManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/DeliveryNotificationManager.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/DeliveryNotificationManager.cpp.i
.PHONY : networkplayground/src/networking/DeliveryNotificationManager.cpp.i

networkplayground/src/networking/DeliveryNotificationManager.s: networkplayground/src/networking/DeliveryNotificationManager.cpp.s

.PHONY : networkplayground/src/networking/DeliveryNotificationManager.s

# target to generate assembly for a file
networkplayground/src/networking/DeliveryNotificationManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/DeliveryNotificationManager.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/DeliveryNotificationManager.cpp.s
.PHONY : networkplayground/src/networking/DeliveryNotificationManager.cpp.s

networkplayground/src/networking/InFlightPacket.o: networkplayground/src/networking/InFlightPacket.cpp.o

.PHONY : networkplayground/src/networking/InFlightPacket.o

# target to build an object file
networkplayground/src/networking/InFlightPacket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/InFlightPacket.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/InFlightPacket.cpp.o
.PHONY : networkplayground/src/networking/InFlightPacket.cpp.o

networkplayground/src/networking/InFlightPacket.i: networkplayground/src/networking/InFlightPacket.cpp.i

.PHONY : networkplayground/src/networking/InFlightPacket.i

# target to preprocess a source file
networkplayground/src/networking/InFlightPacket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/InFlightPacket.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/InFlightPacket.cpp.i
.PHONY : networkplayground/src/networking/InFlightPacket.cpp.i

networkplayground/src/networking/InFlightPacket.s: networkplayground/src/networking/InFlightPacket.cpp.s

.PHONY : networkplayground/src/networking/InFlightPacket.s

# target to generate assembly for a file
networkplayground/src/networking/InFlightPacket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/InFlightPacket.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/InFlightPacket.cpp.s
.PHONY : networkplayground/src/networking/InFlightPacket.cpp.s

networkplayground/src/networking/Logger.o: networkplayground/src/networking/Logger.cpp.o

.PHONY : networkplayground/src/networking/Logger.o

# target to build an object file
networkplayground/src/networking/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/Logger.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/Logger.cpp.o
.PHONY : networkplayground/src/networking/Logger.cpp.o

networkplayground/src/networking/Logger.i: networkplayground/src/networking/Logger.cpp.i

.PHONY : networkplayground/src/networking/Logger.i

# target to preprocess a source file
networkplayground/src/networking/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/Logger.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/Logger.cpp.i
.PHONY : networkplayground/src/networking/Logger.cpp.i

networkplayground/src/networking/Logger.s: networkplayground/src/networking/Logger.cpp.s

.PHONY : networkplayground/src/networking/Logger.s

# target to generate assembly for a file
networkplayground/src/networking/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/Logger.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/Logger.cpp.s
.PHONY : networkplayground/src/networking/Logger.cpp.s

networkplayground/src/networking/NetworkManager.o: networkplayground/src/networking/NetworkManager.cpp.o

.PHONY : networkplayground/src/networking/NetworkManager.o

# target to build an object file
networkplayground/src/networking/NetworkManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/NetworkManager.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/NetworkManager.cpp.o
.PHONY : networkplayground/src/networking/NetworkManager.cpp.o

networkplayground/src/networking/NetworkManager.i: networkplayground/src/networking/NetworkManager.cpp.i

.PHONY : networkplayground/src/networking/NetworkManager.i

# target to preprocess a source file
networkplayground/src/networking/NetworkManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/NetworkManager.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/NetworkManager.cpp.i
.PHONY : networkplayground/src/networking/NetworkManager.cpp.i

networkplayground/src/networking/NetworkManager.s: networkplayground/src/networking/NetworkManager.cpp.s

.PHONY : networkplayground/src/networking/NetworkManager.s

# target to generate assembly for a file
networkplayground/src/networking/NetworkManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/NetworkManager.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/NetworkManager.cpp.s
.PHONY : networkplayground/src/networking/NetworkManager.cpp.s

networkplayground/src/networking/NetworkedData.o: networkplayground/src/networking/NetworkedData.cpp.o

.PHONY : networkplayground/src/networking/NetworkedData.o

# target to build an object file
networkplayground/src/networking/NetworkedData.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/NetworkedData.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/NetworkedData.cpp.o
.PHONY : networkplayground/src/networking/NetworkedData.cpp.o

networkplayground/src/networking/NetworkedData.i: networkplayground/src/networking/NetworkedData.cpp.i

.PHONY : networkplayground/src/networking/NetworkedData.i

# target to preprocess a source file
networkplayground/src/networking/NetworkedData.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/NetworkedData.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/NetworkedData.cpp.i
.PHONY : networkplayground/src/networking/NetworkedData.cpp.i

networkplayground/src/networking/NetworkedData.s: networkplayground/src/networking/NetworkedData.cpp.s

.PHONY : networkplayground/src/networking/NetworkedData.s

# target to generate assembly for a file
networkplayground/src/networking/NetworkedData.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/NetworkedData.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/NetworkedData.cpp.s
.PHONY : networkplayground/src/networking/NetworkedData.cpp.s

networkplayground/src/networking/SocketAddress.o: networkplayground/src/networking/SocketAddress.cpp.o

.PHONY : networkplayground/src/networking/SocketAddress.o

# target to build an object file
networkplayground/src/networking/SocketAddress.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketAddress.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketAddress.cpp.o
.PHONY : networkplayground/src/networking/SocketAddress.cpp.o

networkplayground/src/networking/SocketAddress.i: networkplayground/src/networking/SocketAddress.cpp.i

.PHONY : networkplayground/src/networking/SocketAddress.i

# target to preprocess a source file
networkplayground/src/networking/SocketAddress.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketAddress.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketAddress.cpp.i
.PHONY : networkplayground/src/networking/SocketAddress.cpp.i

networkplayground/src/networking/SocketAddress.s: networkplayground/src/networking/SocketAddress.cpp.s

.PHONY : networkplayground/src/networking/SocketAddress.s

# target to generate assembly for a file
networkplayground/src/networking/SocketAddress.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketAddress.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketAddress.cpp.s
.PHONY : networkplayground/src/networking/SocketAddress.cpp.s

networkplayground/src/networking/SocketAddressFactory.o: networkplayground/src/networking/SocketAddressFactory.cpp.o

.PHONY : networkplayground/src/networking/SocketAddressFactory.o

# target to build an object file
networkplayground/src/networking/SocketAddressFactory.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketAddressFactory.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketAddressFactory.cpp.o
.PHONY : networkplayground/src/networking/SocketAddressFactory.cpp.o

networkplayground/src/networking/SocketAddressFactory.i: networkplayground/src/networking/SocketAddressFactory.cpp.i

.PHONY : networkplayground/src/networking/SocketAddressFactory.i

# target to preprocess a source file
networkplayground/src/networking/SocketAddressFactory.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketAddressFactory.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketAddressFactory.cpp.i
.PHONY : networkplayground/src/networking/SocketAddressFactory.cpp.i

networkplayground/src/networking/SocketAddressFactory.s: networkplayground/src/networking/SocketAddressFactory.cpp.s

.PHONY : networkplayground/src/networking/SocketAddressFactory.s

# target to generate assembly for a file
networkplayground/src/networking/SocketAddressFactory.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketAddressFactory.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketAddressFactory.cpp.s
.PHONY : networkplayground/src/networking/SocketAddressFactory.cpp.s

networkplayground/src/networking/SocketUtil.o: networkplayground/src/networking/SocketUtil.cpp.o

.PHONY : networkplayground/src/networking/SocketUtil.o

# target to build an object file
networkplayground/src/networking/SocketUtil.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketUtil.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketUtil.cpp.o
.PHONY : networkplayground/src/networking/SocketUtil.cpp.o

networkplayground/src/networking/SocketUtil.i: networkplayground/src/networking/SocketUtil.cpp.i

.PHONY : networkplayground/src/networking/SocketUtil.i

# target to preprocess a source file
networkplayground/src/networking/SocketUtil.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketUtil.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketUtil.cpp.i
.PHONY : networkplayground/src/networking/SocketUtil.cpp.i

networkplayground/src/networking/SocketUtil.s: networkplayground/src/networking/SocketUtil.cpp.s

.PHONY : networkplayground/src/networking/SocketUtil.s

# target to generate assembly for a file
networkplayground/src/networking/SocketUtil.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/SocketUtil.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/SocketUtil.cpp.s
.PHONY : networkplayground/src/networking/SocketUtil.cpp.s

networkplayground/src/networking/TCPSocket.o: networkplayground/src/networking/TCPSocket.cpp.o

.PHONY : networkplayground/src/networking/TCPSocket.o

# target to build an object file
networkplayground/src/networking/TCPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/TCPSocket.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/TCPSocket.cpp.o
.PHONY : networkplayground/src/networking/TCPSocket.cpp.o

networkplayground/src/networking/TCPSocket.i: networkplayground/src/networking/TCPSocket.cpp.i

.PHONY : networkplayground/src/networking/TCPSocket.i

# target to preprocess a source file
networkplayground/src/networking/TCPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/TCPSocket.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/TCPSocket.cpp.i
.PHONY : networkplayground/src/networking/TCPSocket.cpp.i

networkplayground/src/networking/TCPSocket.s: networkplayground/src/networking/TCPSocket.cpp.s

.PHONY : networkplayground/src/networking/TCPSocket.s

# target to generate assembly for a file
networkplayground/src/networking/TCPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/TCPSocket.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/TCPSocket.cpp.s
.PHONY : networkplayground/src/networking/TCPSocket.cpp.s

networkplayground/src/networking/UDPSocket.o: networkplayground/src/networking/UDPSocket.cpp.o

.PHONY : networkplayground/src/networking/UDPSocket.o

# target to build an object file
networkplayground/src/networking/UDPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/UDPSocket.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/UDPSocket.cpp.o
.PHONY : networkplayground/src/networking/UDPSocket.cpp.o

networkplayground/src/networking/UDPSocket.i: networkplayground/src/networking/UDPSocket.cpp.i

.PHONY : networkplayground/src/networking/UDPSocket.i

# target to preprocess a source file
networkplayground/src/networking/UDPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/UDPSocket.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/UDPSocket.cpp.i
.PHONY : networkplayground/src/networking/UDPSocket.cpp.i

networkplayground/src/networking/UDPSocket.s: networkplayground/src/networking/UDPSocket.cpp.s

.PHONY : networkplayground/src/networking/UDPSocket.s

# target to generate assembly for a file
networkplayground/src/networking/UDPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/networking/UDPSocket.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/networking/UDPSocket.cpp.s
.PHONY : networkplayground/src/networking/UDPSocket.cpp.s

networkplayground/src/timing/Timing.o: networkplayground/src/timing/Timing.cpp.o

.PHONY : networkplayground/src/timing/Timing.o

# target to build an object file
networkplayground/src/timing/Timing.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/timing/Timing.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/timing/Timing.cpp.o
.PHONY : networkplayground/src/timing/Timing.cpp.o

networkplayground/src/timing/Timing.i: networkplayground/src/timing/Timing.cpp.i

.PHONY : networkplayground/src/timing/Timing.i

# target to preprocess a source file
networkplayground/src/timing/Timing.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/timing/Timing.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/timing/Timing.cpp.i
.PHONY : networkplayground/src/timing/Timing.cpp.i

networkplayground/src/timing/Timing.s: networkplayground/src/timing/Timing.cpp.s

.PHONY : networkplayground/src/timing/Timing.s

# target to generate assembly for a file
networkplayground/src/timing/Timing.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplayground/src/timing/Timing.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplayground/src/timing/Timing.cpp.s
.PHONY : networkplayground/src/timing/Timing.cpp.s

networkplaygroundclient/src/gameobjects/Client.o: networkplaygroundclient/src/gameobjects/Client.cpp.o

.PHONY : networkplaygroundclient/src/gameobjects/Client.o

# target to build an object file
networkplaygroundclient/src/gameobjects/Client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/Client.cpp.o
.PHONY : networkplaygroundclient/src/gameobjects/Client.cpp.o

networkplaygroundclient/src/gameobjects/Client.i: networkplaygroundclient/src/gameobjects/Client.cpp.i

.PHONY : networkplaygroundclient/src/gameobjects/Client.i

# target to preprocess a source file
networkplaygroundclient/src/gameobjects/Client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/Client.cpp.i
.PHONY : networkplaygroundclient/src/gameobjects/Client.cpp.i

networkplaygroundclient/src/gameobjects/Client.s: networkplaygroundclient/src/gameobjects/Client.cpp.s

.PHONY : networkplaygroundclient/src/gameobjects/Client.s

# target to generate assembly for a file
networkplaygroundclient/src/gameobjects/Client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/Client.cpp.s
.PHONY : networkplaygroundclient/src/gameobjects/Client.cpp.s

networkplaygroundclient/src/gameobjects/Ghost.o: networkplaygroundclient/src/gameobjects/Ghost.cpp.o

.PHONY : networkplaygroundclient/src/gameobjects/Ghost.o

# target to build an object file
networkplaygroundclient/src/gameobjects/Ghost.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/Ghost.cpp.o
.PHONY : networkplaygroundclient/src/gameobjects/Ghost.cpp.o

networkplaygroundclient/src/gameobjects/Ghost.i: networkplaygroundclient/src/gameobjects/Ghost.cpp.i

.PHONY : networkplaygroundclient/src/gameobjects/Ghost.i

# target to preprocess a source file
networkplaygroundclient/src/gameobjects/Ghost.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/Ghost.cpp.i
.PHONY : networkplaygroundclient/src/gameobjects/Ghost.cpp.i

networkplaygroundclient/src/gameobjects/Ghost.s: networkplaygroundclient/src/gameobjects/Ghost.cpp.s

.PHONY : networkplaygroundclient/src/gameobjects/Ghost.s

# target to generate assembly for a file
networkplaygroundclient/src/gameobjects/Ghost.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/Ghost.cpp.s
.PHONY : networkplaygroundclient/src/gameobjects/Ghost.cpp.s

networkplaygroundclient/src/gameobjects/PlayerClient.o: networkplaygroundclient/src/gameobjects/PlayerClient.cpp.o

.PHONY : networkplaygroundclient/src/gameobjects/PlayerClient.o

# target to build an object file
networkplaygroundclient/src/gameobjects/PlayerClient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/PlayerClient.cpp.o
.PHONY : networkplaygroundclient/src/gameobjects/PlayerClient.cpp.o

networkplaygroundclient/src/gameobjects/PlayerClient.i: networkplaygroundclient/src/gameobjects/PlayerClient.cpp.i

.PHONY : networkplaygroundclient/src/gameobjects/PlayerClient.i

# target to preprocess a source file
networkplaygroundclient/src/gameobjects/PlayerClient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/PlayerClient.cpp.i
.PHONY : networkplaygroundclient/src/gameobjects/PlayerClient.cpp.i

networkplaygroundclient/src/gameobjects/PlayerClient.s: networkplaygroundclient/src/gameobjects/PlayerClient.cpp.s

.PHONY : networkplaygroundclient/src/gameobjects/PlayerClient.s

# target to generate assembly for a file
networkplaygroundclient/src/gameobjects/PlayerClient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/gameobjects/PlayerClient.cpp.s
.PHONY : networkplaygroundclient/src/gameobjects/PlayerClient.cpp.s

networkplaygroundclient/src/graphics/GraphicsDriver.o: networkplaygroundclient/src/graphics/GraphicsDriver.cpp.o

.PHONY : networkplaygroundclient/src/graphics/GraphicsDriver.o

# target to build an object file
networkplaygroundclient/src/graphics/GraphicsDriver.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/GraphicsDriver.cpp.o
.PHONY : networkplaygroundclient/src/graphics/GraphicsDriver.cpp.o

networkplaygroundclient/src/graphics/GraphicsDriver.i: networkplaygroundclient/src/graphics/GraphicsDriver.cpp.i

.PHONY : networkplaygroundclient/src/graphics/GraphicsDriver.i

# target to preprocess a source file
networkplaygroundclient/src/graphics/GraphicsDriver.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/GraphicsDriver.cpp.i
.PHONY : networkplaygroundclient/src/graphics/GraphicsDriver.cpp.i

networkplaygroundclient/src/graphics/GraphicsDriver.s: networkplaygroundclient/src/graphics/GraphicsDriver.cpp.s

.PHONY : networkplaygroundclient/src/graphics/GraphicsDriver.s

# target to generate assembly for a file
networkplaygroundclient/src/graphics/GraphicsDriver.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/GraphicsDriver.cpp.s
.PHONY : networkplaygroundclient/src/graphics/GraphicsDriver.cpp.s

networkplaygroundclient/src/graphics/RenderManager.o: networkplaygroundclient/src/graphics/RenderManager.cpp.o

.PHONY : networkplaygroundclient/src/graphics/RenderManager.o

# target to build an object file
networkplaygroundclient/src/graphics/RenderManager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/RenderManager.cpp.o
.PHONY : networkplaygroundclient/src/graphics/RenderManager.cpp.o

networkplaygroundclient/src/graphics/RenderManager.i: networkplaygroundclient/src/graphics/RenderManager.cpp.i

.PHONY : networkplaygroundclient/src/graphics/RenderManager.i

# target to preprocess a source file
networkplaygroundclient/src/graphics/RenderManager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/RenderManager.cpp.i
.PHONY : networkplaygroundclient/src/graphics/RenderManager.cpp.i

networkplaygroundclient/src/graphics/RenderManager.s: networkplaygroundclient/src/graphics/RenderManager.cpp.s

.PHONY : networkplaygroundclient/src/graphics/RenderManager.s

# target to generate assembly for a file
networkplaygroundclient/src/graphics/RenderManager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/RenderManager.cpp.s
.PHONY : networkplaygroundclient/src/graphics/RenderManager.cpp.s

networkplaygroundclient/src/graphics/SpriteComponent.o: networkplaygroundclient/src/graphics/SpriteComponent.cpp.o

.PHONY : networkplaygroundclient/src/graphics/SpriteComponent.o

# target to build an object file
networkplaygroundclient/src/graphics/SpriteComponent.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/SpriteComponent.cpp.o
.PHONY : networkplaygroundclient/src/graphics/SpriteComponent.cpp.o

networkplaygroundclient/src/graphics/SpriteComponent.i: networkplaygroundclient/src/graphics/SpriteComponent.cpp.i

.PHONY : networkplaygroundclient/src/graphics/SpriteComponent.i

# target to preprocess a source file
networkplaygroundclient/src/graphics/SpriteComponent.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/SpriteComponent.cpp.i
.PHONY : networkplaygroundclient/src/graphics/SpriteComponent.cpp.i

networkplaygroundclient/src/graphics/SpriteComponent.s: networkplaygroundclient/src/graphics/SpriteComponent.cpp.s

.PHONY : networkplaygroundclient/src/graphics/SpriteComponent.s

# target to generate assembly for a file
networkplaygroundclient/src/graphics/SpriteComponent.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/SpriteComponent.cpp.s
.PHONY : networkplaygroundclient/src/graphics/SpriteComponent.cpp.s

networkplaygroundclient/src/graphics/TextureManager.o: networkplaygroundclient/src/graphics/TextureManager.cpp.o

.PHONY : networkplaygroundclient/src/graphics/TextureManager.o

# target to build an object file
networkplaygroundclient/src/graphics/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/TextureManager.cpp.o
.PHONY : networkplaygroundclient/src/graphics/TextureManager.cpp.o

networkplaygroundclient/src/graphics/TextureManager.i: networkplaygroundclient/src/graphics/TextureManager.cpp.i

.PHONY : networkplaygroundclient/src/graphics/TextureManager.i

# target to preprocess a source file
networkplaygroundclient/src/graphics/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/TextureManager.cpp.i
.PHONY : networkplaygroundclient/src/graphics/TextureManager.cpp.i

networkplaygroundclient/src/graphics/TextureManager.s: networkplaygroundclient/src/graphics/TextureManager.cpp.s

.PHONY : networkplaygroundclient/src/graphics/TextureManager.s

# target to generate assembly for a file
networkplaygroundclient/src/graphics/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/TextureManager.cpp.s
.PHONY : networkplaygroundclient/src/graphics/TextureManager.cpp.s

networkplaygroundclient/src/graphics/WindowManager.o: networkplaygroundclient/src/graphics/WindowManager.cpp.o

.PHONY : networkplaygroundclient/src/graphics/WindowManager.o

# target to build an object file
networkplaygroundclient/src/graphics/WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/WindowManager.cpp.o
.PHONY : networkplaygroundclient/src/graphics/WindowManager.cpp.o

networkplaygroundclient/src/graphics/WindowManager.i: networkplaygroundclient/src/graphics/WindowManager.cpp.i

.PHONY : networkplaygroundclient/src/graphics/WindowManager.i

# target to preprocess a source file
networkplaygroundclient/src/graphics/WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/WindowManager.cpp.i
.PHONY : networkplaygroundclient/src/graphics/WindowManager.cpp.i

networkplaygroundclient/src/graphics/WindowManager.s: networkplaygroundclient/src/graphics/WindowManager.cpp.s

.PHONY : networkplaygroundclient/src/graphics/WindowManager.s

# target to generate assembly for a file
networkplaygroundclient/src/graphics/WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/graphics/WindowManager.cpp.s
.PHONY : networkplaygroundclient/src/graphics/WindowManager.cpp.s

networkplaygroundclient/src/input/InputManager.o: networkplaygroundclient/src/input/InputManager.cpp.o

.PHONY : networkplaygroundclient/src/input/InputManager.o

# target to build an object file
networkplaygroundclient/src/input/InputManager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/input/InputManager.cpp.o
.PHONY : networkplaygroundclient/src/input/InputManager.cpp.o

networkplaygroundclient/src/input/InputManager.i: networkplaygroundclient/src/input/InputManager.cpp.i

.PHONY : networkplaygroundclient/src/input/InputManager.i

# target to preprocess a source file
networkplaygroundclient/src/input/InputManager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/input/InputManager.cpp.i
.PHONY : networkplaygroundclient/src/input/InputManager.cpp.i

networkplaygroundclient/src/input/InputManager.s: networkplaygroundclient/src/input/InputManager.cpp.s

.PHONY : networkplaygroundclient/src/input/InputManager.s

# target to generate assembly for a file
networkplaygroundclient/src/input/InputManager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/input/InputManager.cpp.s
.PHONY : networkplaygroundclient/src/input/InputManager.cpp.s

networkplaygroundclient/src/main.o: networkplaygroundclient/src/main.cpp.o

.PHONY : networkplaygroundclient/src/main.o

# target to build an object file
networkplaygroundclient/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/main.cpp.o
.PHONY : networkplaygroundclient/src/main.cpp.o

networkplaygroundclient/src/main.i: networkplaygroundclient/src/main.cpp.i

.PHONY : networkplaygroundclient/src/main.i

# target to preprocess a source file
networkplaygroundclient/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/main.cpp.i
.PHONY : networkplaygroundclient/src/main.cpp.i

networkplaygroundclient/src/main.s: networkplaygroundclient/src/main.cpp.s

.PHONY : networkplaygroundclient/src/main.s

# target to generate assembly for a file
networkplaygroundclient/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/main.cpp.s
.PHONY : networkplaygroundclient/src/main.cpp.s

networkplaygroundclient/src/networking/NetworkManagerClient.o: networkplaygroundclient/src/networking/NetworkManagerClient.cpp.o

.PHONY : networkplaygroundclient/src/networking/NetworkManagerClient.o

# target to build an object file
networkplaygroundclient/src/networking/NetworkManagerClient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/networking/NetworkManagerClient.cpp.o
.PHONY : networkplaygroundclient/src/networking/NetworkManagerClient.cpp.o

networkplaygroundclient/src/networking/NetworkManagerClient.i: networkplaygroundclient/src/networking/NetworkManagerClient.cpp.i

.PHONY : networkplaygroundclient/src/networking/NetworkManagerClient.i

# target to preprocess a source file
networkplaygroundclient/src/networking/NetworkManagerClient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/networking/NetworkManagerClient.cpp.i
.PHONY : networkplaygroundclient/src/networking/NetworkManagerClient.cpp.i

networkplaygroundclient/src/networking/NetworkManagerClient.s: networkplaygroundclient/src/networking/NetworkManagerClient.cpp.s

.PHONY : networkplaygroundclient/src/networking/NetworkManagerClient.s

# target to generate assembly for a file
networkplaygroundclient/src/networking/NetworkManagerClient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/networking/NetworkManagerClient.cpp.s
.PHONY : networkplaygroundclient/src/networking/NetworkManagerClient.cpp.s

networkplaygroundclient/src/networking/ReplicationManagerClient.o: networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.o

.PHONY : networkplaygroundclient/src/networking/ReplicationManagerClient.o

# target to build an object file
networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.o
.PHONY : networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.o

networkplaygroundclient/src/networking/ReplicationManagerClient.i: networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.i

.PHONY : networkplaygroundclient/src/networking/ReplicationManagerClient.i

# target to preprocess a source file
networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.i
.PHONY : networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.i

networkplaygroundclient/src/networking/ReplicationManagerClient.s: networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.s

.PHONY : networkplaygroundclient/src/networking/ReplicationManagerClient.s

# target to generate assembly for a file
networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.s
.PHONY : networkplaygroundclient/src/networking/ReplicationManagerClient.cpp.s

networkplaygroundserver/src/gameobjects/PlayerServer.o: networkplaygroundserver/src/gameobjects/PlayerServer.cpp.o

.PHONY : networkplaygroundserver/src/gameobjects/PlayerServer.o

# target to build an object file
networkplaygroundserver/src/gameobjects/PlayerServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/gameobjects/PlayerServer.cpp.o
.PHONY : networkplaygroundserver/src/gameobjects/PlayerServer.cpp.o

networkplaygroundserver/src/gameobjects/PlayerServer.i: networkplaygroundserver/src/gameobjects/PlayerServer.cpp.i

.PHONY : networkplaygroundserver/src/gameobjects/PlayerServer.i

# target to preprocess a source file
networkplaygroundserver/src/gameobjects/PlayerServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/gameobjects/PlayerServer.cpp.i
.PHONY : networkplaygroundserver/src/gameobjects/PlayerServer.cpp.i

networkplaygroundserver/src/gameobjects/PlayerServer.s: networkplaygroundserver/src/gameobjects/PlayerServer.cpp.s

.PHONY : networkplaygroundserver/src/gameobjects/PlayerServer.s

# target to generate assembly for a file
networkplaygroundserver/src/gameobjects/PlayerServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/gameobjects/PlayerServer.cpp.s
.PHONY : networkplaygroundserver/src/gameobjects/PlayerServer.cpp.s

networkplaygroundserver/src/main.o: networkplaygroundserver/src/main.cpp.o

.PHONY : networkplaygroundserver/src/main.o

# target to build an object file
networkplaygroundserver/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/main.cpp.o
.PHONY : networkplaygroundserver/src/main.cpp.o

networkplaygroundserver/src/main.i: networkplaygroundserver/src/main.cpp.i

.PHONY : networkplaygroundserver/src/main.i

# target to preprocess a source file
networkplaygroundserver/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/main.cpp.i
.PHONY : networkplaygroundserver/src/main.cpp.i

networkplaygroundserver/src/main.s: networkplaygroundserver/src/main.cpp.s

.PHONY : networkplaygroundserver/src/main.s

# target to generate assembly for a file
networkplaygroundserver/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/main.cpp.s
.PHONY : networkplaygroundserver/src/main.cpp.s

networkplaygroundserver/src/networking/ClientProxy.o: networkplaygroundserver/src/networking/ClientProxy.cpp.o

.PHONY : networkplaygroundserver/src/networking/ClientProxy.o

# target to build an object file
networkplaygroundserver/src/networking/ClientProxy.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ClientProxy.cpp.o
.PHONY : networkplaygroundserver/src/networking/ClientProxy.cpp.o

networkplaygroundserver/src/networking/ClientProxy.i: networkplaygroundserver/src/networking/ClientProxy.cpp.i

.PHONY : networkplaygroundserver/src/networking/ClientProxy.i

# target to preprocess a source file
networkplaygroundserver/src/networking/ClientProxy.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ClientProxy.cpp.i
.PHONY : networkplaygroundserver/src/networking/ClientProxy.cpp.i

networkplaygroundserver/src/networking/ClientProxy.s: networkplaygroundserver/src/networking/ClientProxy.cpp.s

.PHONY : networkplaygroundserver/src/networking/ClientProxy.s

# target to generate assembly for a file
networkplaygroundserver/src/networking/ClientProxy.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ClientProxy.cpp.s
.PHONY : networkplaygroundserver/src/networking/ClientProxy.cpp.s

networkplaygroundserver/src/networking/NetworkManagerServer.o: networkplaygroundserver/src/networking/NetworkManagerServer.cpp.o

.PHONY : networkplaygroundserver/src/networking/NetworkManagerServer.o

# target to build an object file
networkplaygroundserver/src/networking/NetworkManagerServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/NetworkManagerServer.cpp.o
.PHONY : networkplaygroundserver/src/networking/NetworkManagerServer.cpp.o

networkplaygroundserver/src/networking/NetworkManagerServer.i: networkplaygroundserver/src/networking/NetworkManagerServer.cpp.i

.PHONY : networkplaygroundserver/src/networking/NetworkManagerServer.i

# target to preprocess a source file
networkplaygroundserver/src/networking/NetworkManagerServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/NetworkManagerServer.cpp.i
.PHONY : networkplaygroundserver/src/networking/NetworkManagerServer.cpp.i

networkplaygroundserver/src/networking/NetworkManagerServer.s: networkplaygroundserver/src/networking/NetworkManagerServer.cpp.s

.PHONY : networkplaygroundserver/src/networking/NetworkManagerServer.s

# target to generate assembly for a file
networkplaygroundserver/src/networking/NetworkManagerServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/NetworkManagerServer.cpp.s
.PHONY : networkplaygroundserver/src/networking/NetworkManagerServer.cpp.s

networkplaygroundserver/src/networking/ReplicationManagerServer.o: networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.o

.PHONY : networkplaygroundserver/src/networking/ReplicationManagerServer.o

# target to build an object file
networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.o
.PHONY : networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.o

networkplaygroundserver/src/networking/ReplicationManagerServer.i: networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.i

.PHONY : networkplaygroundserver/src/networking/ReplicationManagerServer.i

# target to preprocess a source file
networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.i
.PHONY : networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.i

networkplaygroundserver/src/networking/ReplicationManagerServer.s: networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.s

.PHONY : networkplaygroundserver/src/networking/ReplicationManagerServer.s

# target to generate assembly for a file
networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.s
.PHONY : networkplaygroundserver/src/networking/ReplicationManagerServer.cpp.s

networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.o: networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.o

.PHONY : networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.o

# target to build an object file
networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.o
.PHONY : networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.o

networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.i: networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.i

.PHONY : networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.i

# target to preprocess a source file
networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.i
.PHONY : networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.i

networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.s: networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.s

.PHONY : networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.s

# target to generate assembly for a file
networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.s
.PHONY : networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.cpp.s

networkplaygroundserver/src/networking/Server.o: networkplaygroundserver/src/networking/Server.cpp.o

.PHONY : networkplaygroundserver/src/networking/Server.o

# target to build an object file
networkplaygroundserver/src/networking/Server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/Server.cpp.o
.PHONY : networkplaygroundserver/src/networking/Server.cpp.o

networkplaygroundserver/src/networking/Server.i: networkplaygroundserver/src/networking/Server.cpp.i

.PHONY : networkplaygroundserver/src/networking/Server.i

# target to preprocess a source file
networkplaygroundserver/src/networking/Server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/Server.cpp.i
.PHONY : networkplaygroundserver/src/networking/Server.cpp.i

networkplaygroundserver/src/networking/Server.s: networkplaygroundserver/src/networking/Server.cpp.s

.PHONY : networkplaygroundserver/src/networking/Server.s

# target to generate assembly for a file
networkplaygroundserver/src/networking/Server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/src/networking/Server.cpp.s
.PHONY : networkplaygroundserver/src/networking/Server.cpp.s

networkplaygroundserver/tests/tests.o: networkplaygroundserver/tests/tests.cpp.o

.PHONY : networkplaygroundserver/tests/tests.o

# target to build an object file
networkplaygroundserver/tests/tests.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/tests/tests.cpp.o
.PHONY : networkplaygroundserver/tests/tests.cpp.o

networkplaygroundserver/tests/tests.i: networkplaygroundserver/tests/tests.cpp.i

.PHONY : networkplaygroundserver/tests/tests.i

# target to preprocess a source file
networkplaygroundserver/tests/tests.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/tests/tests.cpp.i
.PHONY : networkplaygroundserver/tests/tests.cpp.i

networkplaygroundserver/tests/tests.s: networkplaygroundserver/tests/tests.cpp.s

.PHONY : networkplaygroundserver/tests/tests.s

# target to generate assembly for a file
networkplaygroundserver/tests/tests.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/networkplaygroundserver/tests/tests.cpp.s
.PHONY : networkplaygroundserver/tests/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server"
	@echo "... client"
	@echo "... networkplayground/src/IO/MemoryBitStream.o"
	@echo "... networkplayground/src/IO/MemoryBitStream.i"
	@echo "... networkplayground/src/IO/MemoryBitStream.s"
	@echo "... networkplayground/src/gameobjects/Engine.o"
	@echo "... networkplayground/src/gameobjects/Engine.i"
	@echo "... networkplayground/src/gameobjects/Engine.s"
	@echo "... networkplayground/src/gameobjects/GameObject.o"
	@echo "... networkplayground/src/gameobjects/GameObject.i"
	@echo "... networkplayground/src/gameobjects/GameObject.s"
	@echo "... networkplayground/src/gameobjects/GameObjectRegistry.o"
	@echo "... networkplayground/src/gameobjects/GameObjectRegistry.i"
	@echo "... networkplayground/src/gameobjects/GameObjectRegistry.s"
	@echo "... networkplayground/src/gameobjects/InputState.o"
	@echo "... networkplayground/src/gameobjects/InputState.i"
	@echo "... networkplayground/src/gameobjects/InputState.s"
	@echo "... networkplayground/src/gameobjects/Move.o"
	@echo "... networkplayground/src/gameobjects/Move.i"
	@echo "... networkplayground/src/gameobjects/Move.s"
	@echo "... networkplayground/src/gameobjects/MoveList.o"
	@echo "... networkplayground/src/gameobjects/MoveList.i"
	@echo "... networkplayground/src/gameobjects/MoveList.s"
	@echo "... networkplayground/src/gameobjects/Player.o"
	@echo "... networkplayground/src/gameobjects/Player.i"
	@echo "... networkplayground/src/gameobjects/Player.s"
	@echo "... networkplayground/src/gameobjects/PlayerMessage.o"
	@echo "... networkplayground/src/gameobjects/PlayerMessage.i"
	@echo "... networkplayground/src/gameobjects/PlayerMessage.s"
	@echo "... networkplayground/src/gameobjects/World.o"
	@echo "... networkplayground/src/gameobjects/World.i"
	@echo "... networkplayground/src/gameobjects/World.s"
	@echo "... networkplayground/src/math/Vector3.o"
	@echo "... networkplayground/src/math/Vector3.i"
	@echo "... networkplayground/src/math/Vector3.s"
	@echo "... networkplayground/src/networking/AckRange.o"
	@echo "... networkplayground/src/networking/AckRange.i"
	@echo "... networkplayground/src/networking/AckRange.s"
	@echo "... networkplayground/src/networking/DeliveryNotificationManager.o"
	@echo "... networkplayground/src/networking/DeliveryNotificationManager.i"
	@echo "... networkplayground/src/networking/DeliveryNotificationManager.s"
	@echo "... networkplayground/src/networking/InFlightPacket.o"
	@echo "... networkplayground/src/networking/InFlightPacket.i"
	@echo "... networkplayground/src/networking/InFlightPacket.s"
	@echo "... networkplayground/src/networking/Logger.o"
	@echo "... networkplayground/src/networking/Logger.i"
	@echo "... networkplayground/src/networking/Logger.s"
	@echo "... networkplayground/src/networking/NetworkManager.o"
	@echo "... networkplayground/src/networking/NetworkManager.i"
	@echo "... networkplayground/src/networking/NetworkManager.s"
	@echo "... networkplayground/src/networking/NetworkedData.o"
	@echo "... networkplayground/src/networking/NetworkedData.i"
	@echo "... networkplayground/src/networking/NetworkedData.s"
	@echo "... networkplayground/src/networking/SocketAddress.o"
	@echo "... networkplayground/src/networking/SocketAddress.i"
	@echo "... networkplayground/src/networking/SocketAddress.s"
	@echo "... networkplayground/src/networking/SocketAddressFactory.o"
	@echo "... networkplayground/src/networking/SocketAddressFactory.i"
	@echo "... networkplayground/src/networking/SocketAddressFactory.s"
	@echo "... networkplayground/src/networking/SocketUtil.o"
	@echo "... networkplayground/src/networking/SocketUtil.i"
	@echo "... networkplayground/src/networking/SocketUtil.s"
	@echo "... networkplayground/src/networking/TCPSocket.o"
	@echo "... networkplayground/src/networking/TCPSocket.i"
	@echo "... networkplayground/src/networking/TCPSocket.s"
	@echo "... networkplayground/src/networking/UDPSocket.o"
	@echo "... networkplayground/src/networking/UDPSocket.i"
	@echo "... networkplayground/src/networking/UDPSocket.s"
	@echo "... networkplayground/src/timing/Timing.o"
	@echo "... networkplayground/src/timing/Timing.i"
	@echo "... networkplayground/src/timing/Timing.s"
	@echo "... networkplaygroundclient/src/gameobjects/Client.o"
	@echo "... networkplaygroundclient/src/gameobjects/Client.i"
	@echo "... networkplaygroundclient/src/gameobjects/Client.s"
	@echo "... networkplaygroundclient/src/gameobjects/Ghost.o"
	@echo "... networkplaygroundclient/src/gameobjects/Ghost.i"
	@echo "... networkplaygroundclient/src/gameobjects/Ghost.s"
	@echo "... networkplaygroundclient/src/gameobjects/PlayerClient.o"
	@echo "... networkplaygroundclient/src/gameobjects/PlayerClient.i"
	@echo "... networkplaygroundclient/src/gameobjects/PlayerClient.s"
	@echo "... networkplaygroundclient/src/graphics/GraphicsDriver.o"
	@echo "... networkplaygroundclient/src/graphics/GraphicsDriver.i"
	@echo "... networkplaygroundclient/src/graphics/GraphicsDriver.s"
	@echo "... networkplaygroundclient/src/graphics/RenderManager.o"
	@echo "... networkplaygroundclient/src/graphics/RenderManager.i"
	@echo "... networkplaygroundclient/src/graphics/RenderManager.s"
	@echo "... networkplaygroundclient/src/graphics/SpriteComponent.o"
	@echo "... networkplaygroundclient/src/graphics/SpriteComponent.i"
	@echo "... networkplaygroundclient/src/graphics/SpriteComponent.s"
	@echo "... networkplaygroundclient/src/graphics/TextureManager.o"
	@echo "... networkplaygroundclient/src/graphics/TextureManager.i"
	@echo "... networkplaygroundclient/src/graphics/TextureManager.s"
	@echo "... networkplaygroundclient/src/graphics/WindowManager.o"
	@echo "... networkplaygroundclient/src/graphics/WindowManager.i"
	@echo "... networkplaygroundclient/src/graphics/WindowManager.s"
	@echo "... networkplaygroundclient/src/input/InputManager.o"
	@echo "... networkplaygroundclient/src/input/InputManager.i"
	@echo "... networkplaygroundclient/src/input/InputManager.s"
	@echo "... networkplaygroundclient/src/main.o"
	@echo "... networkplaygroundclient/src/main.i"
	@echo "... networkplaygroundclient/src/main.s"
	@echo "... networkplaygroundclient/src/networking/NetworkManagerClient.o"
	@echo "... networkplaygroundclient/src/networking/NetworkManagerClient.i"
	@echo "... networkplaygroundclient/src/networking/NetworkManagerClient.s"
	@echo "... networkplaygroundclient/src/networking/ReplicationManagerClient.o"
	@echo "... networkplaygroundclient/src/networking/ReplicationManagerClient.i"
	@echo "... networkplaygroundclient/src/networking/ReplicationManagerClient.s"
	@echo "... networkplaygroundserver/src/gameobjects/PlayerServer.o"
	@echo "... networkplaygroundserver/src/gameobjects/PlayerServer.i"
	@echo "... networkplaygroundserver/src/gameobjects/PlayerServer.s"
	@echo "... networkplaygroundserver/src/main.o"
	@echo "... networkplaygroundserver/src/main.i"
	@echo "... networkplaygroundserver/src/main.s"
	@echo "... networkplaygroundserver/src/networking/ClientProxy.o"
	@echo "... networkplaygroundserver/src/networking/ClientProxy.i"
	@echo "... networkplaygroundserver/src/networking/ClientProxy.s"
	@echo "... networkplaygroundserver/src/networking/NetworkManagerServer.o"
	@echo "... networkplaygroundserver/src/networking/NetworkManagerServer.i"
	@echo "... networkplaygroundserver/src/networking/NetworkManagerServer.s"
	@echo "... networkplaygroundserver/src/networking/ReplicationManagerServer.o"
	@echo "... networkplaygroundserver/src/networking/ReplicationManagerServer.i"
	@echo "... networkplaygroundserver/src/networking/ReplicationManagerServer.s"
	@echo "... networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.o"
	@echo "... networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.i"
	@echo "... networkplaygroundserver/src/networking/ReplicationManagerTransmissionData.s"
	@echo "... networkplaygroundserver/src/networking/Server.o"
	@echo "... networkplaygroundserver/src/networking/Server.i"
	@echo "... networkplaygroundserver/src/networking/Server.s"
	@echo "... networkplaygroundserver/tests/tests.o"
	@echo "... networkplaygroundserver/tests/tests.i"
	@echo "... networkplaygroundserver/tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

